### ISSUE TITLE
Will a failed deploy leave the project in a sane state?

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#135]
- [x] Intentionally make a cap deploy fail. Does a failed deploy leave the site in a broken state? Or does it, as advertised, not change what appears on the server to end users?

**Comment by sgurnick** [comment]
I tested the following `cap deploy` failure scenarios on the ursus-dev server:
- failure **before** `deploy:symlink:release` (_no changes to the database_)
  - site is still available/accessible with previous release still active
  - no further action required to ensure stability
- failure **before** `deploy:symlink:release` **after** `db:migrate` (_changes to the database occurred_)
  - the symlink of `current` is still set to the prior release and the prior release is still being served by httpd
  - depending on the database changes that occurred, the site _could_ be unstable or worst case unavailable
  - manual intervention/rollback might be necessary to ensure stability
- failure **during** `db:migrate` (_changes to the database occurred_)
    - depending what was changed with the database (and what failed during the migration) this _could_ result in a site that is unavailable
   - even if the site is still accessible, the database changes _could_ impact site functionality
   - manual intervention/rollback is most likely necessary to ensure site stability
- failure **after** `deploy:symlink:release` and **before** passenger/httpd restart
  - the symlink of `current` to the new release was established, but since passenger/httpd was not restarted, the prior release is still being served
  - while the site is still online, we are operating in a "split-brain" mode, where the `/opt/ursus/current` directory points to the new release, but the prior release is still being served via httpd
  - **if database migrations took place** in this deploy, this _could_ affect functionality and site stability - manual intervention/rollback is most likely necessary
  - **if no database migrations occurred**, then the site is most likely stable while troubleshooting takes place and a new deploy is executed
