### ISSUE TITLE
Add a route to Ursus to resolve Arks to redirect to a matching item page

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/ursus#138]
It should be possible to write a route to provide a URL for Ursus which will redirect from, for example: 

https://ursus-stage.library.ucla.edu/ark/13030/hb7k4007rb

should redirect to:
https://ursus-stage.library.ucla.edu/catalog/1z40ks800

**Comment by emcaulay** [comment]
Very interesting ticket. 

I think that story needs more work from someone like Sharon? I would say the story is something more like:

As a user who has referenced an LADNN image about the history of Neighborhood Watch at this URL (http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz0002q3cq) on multiple occasions, I expect the URL to work in the future. If you switch to a new system, that shouldn't mean I, the user, have to do more work. Especially since you don't know I have stored that URL and am using it in my dissertation.

**Comment by hardyoyo** [comment]
note that what I'm proposing is a redirect... the URL the user will use will *not* be the same thing they see in their browser when they land on what they asked for. This is definitely not a replacement for a full-scale ID discussion... it's mostly a bandaid so there's *a way* to get from what we already know (the ark) to the new location.

**Comment by sshaferUCLA** [comment]
**Google Search**
As a user doing a search in Google, when I click on a SERP leading to an item in a UCLA Library Collection in Samvera, I expect to be able to navigate to other items in the same collection via breadcrumbs or editing the URL directly. I don't want to be on an "island" with no connection to the collection. 

**Existing digital2 URL**
As a user (or bot), clicking on an existing digital2 URL, I expect to land on the cited item.

**Analytics**
As a library staff member, I expect the ability to use Google Analytics to produce reports at the Collection level in order to help Library administration and Donors make data-informed decisions at the collection level

**Scenarios for redirect**

1. digital2 Collection has been ingested in to Samvera and taken down from digital2 so there is a need to redirect from digital2 item to Samvera item

2. Samvera collection(s) URL path changes x times over y period (production)

3. all the wild DLP urls in the public need redirect to Samvera (e.g. LIT250 - but there aren't that many and it is already taken down)

4. all the urls pointing from known resources (Calisphere) need to be systematically updated -- or just go through redirect - but it would be better to change the source URL

5. We should get a report of where referrals come from (to collections in digital2) and try to make the source update to the new URL if possible

**Comment by mark-dce** [comment]
Superseded by requirements expressed in #270
