### ISSUE TITLE
Public: header links

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#15]
Add homepage header links to the existing pages for
- ~~Mission~~
- ~~Services~~
- ~~Digitization Criteria~~

[ Moved to footer - Andy 10/17]
- ~~Copyright and Collections (http://digital2.library.ucla.edu/copyright.html)~~
- ~~Contact (http://digital2.library.ucla.edu/contact.html)~~

Layout doesn't need to match exactly as long as there are links

child of https://github.com/UCLALibrary/amalgamated-samvera/issues/129

<img width="990" alt="129 - homepage header" src="https://user-images.githubusercontent.com/3064318/46978190-1d8eef80-d083-11e8-940f-6ff71110d829.png">

**Comment by little9** [comment]
@emcaulay 

This PR changes it from looking like this:
![Screenshot_2018-10-17 Blacklight.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417773e7853e3097c84e023b34b7c091b4d52be011a001ea9aacd39aca4392289095fecd5655625c63440f9b8821eed07b3278d4e80a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59a42c058f049e14553a31b242e.png)

to this (with two links instead of a logo):
![Screenshot_2018-10-17 Blacklight(1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6417773e7853e3097c84e023b34b7c091b474fb553444d04bea6d37ef5f22e7a985959ee84395e70ce3440acb1d34abf01bb728d4682b0bd8f5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5bff43e14b57a21b3662e4647b.png)

Was that your intention with the comments you made on this ticket or did you want a logo and two links?

**Comment by emcaulay** [comment]
I like the logo with the logo being also a linked image. That is, I prefer the first image.
