### ISSUE TITLE
Public: Metadata on single item view

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#17]
The following fields should appear on a single item view page (a.k.a. a work show screen)

**NOTE** Fields should be displayed without solr suffixes

- [x] Title
- [x] Identifier (item ark)
- [x] Subject
- [x] Resource Type
- [x] Copyright Status
- [x] Genre
- [x] Named Subject
- [x] Repository
- [x] Publisher
- [x] Rights (country of creation)
- [x] Rights Holder
- [x] Normalized Date
- [x] Local Identifier (not the ark -- this is the dc11 identifier, a.k.a. the local_identifier field)
- [x] Date Created
- [x] Medium (See "Group of women dressed in identical outfits": not all records have this value)
- [x] Extent (See "Group of women dressed in identical outfits": not all records have this value)
- [x] Dimensions (See "Group of women dressed in identical outfits": not all records have this value)
- [x] Funding Note (See "Maria Reeves, posed for a photograph on a patio chair, 1920s."; not all records have this value)
- [x] Latitude (See "Communion at Plaza Church, Los Angeles, 1942-1952"; not all records have this value)
- [x] Longitude (See "Communion at Plaza Church, Los Angeles, 1942-1952"; not all records have this value)
- [x] Caption (See "Telles family at the Sleepy Lagoon murder case acquittal"; not all records have this value)
- [x] Language
- [x] Photographer

**Comment by val99erie** [comment]
Latitude and Longitude will be displayed in a single field called Geographic Coordinates, per story #22.

**Comment by val99erie** [comment]
Depends on #281

**Comment by val99erie** [comment]
@emcaulay I want to draw your attention to something:

In my dev environment, when I adjust the browser window to be very wide (so that the labels appear to the left side of the metadata values) the label for `Rights (country of creation)` gets truncated because of the way the page is layed out (i.e. the column for the labels is slightly too narrow for the longest label).  We might want to add a story to adjust the style of the page.

<img width="587" alt="truncated_label" src="https://user-images.githubusercontent.com/298865/47464969-9cd1a100-d7b0-11e8-8850-e35248af0b6a.png">
