### ISSUE TITLE
"Network error" message from 'cite this item'

### ISSUE THREAD

**Issue by sshaferUCLA** [UCLALibrary/ursus#249]

**Comment by sshaferUCLA** [comment]
ursus-test.library.ucla.edu
Chrome

select facet = A sample collection for Thursday

select item https://ursus-test.library.ucla.edu/catalog/ws859g020

click on 'cite this item'

obtain 'Network error'

**Comment by emcaulay** [comment]
I've put this ticket at the top of the backlog. @little9 and @jendiamond  are working on upgrading to Blacklight 7 and this might be something they are actively working on. Since this is happening in test, I'm not putting the ticket into Sprint 15 at this time. I will wait to just hear from Jamie and Jen that this is "Yeah, we know. we'll get it fixed as part of the Blacklight 7 upgrade."

**Comment by little9** [comment]
@emcaulay @sshaferUCLA I took a look at this after the Blacklight upgrade and it's still happening so that didn't fix this as side effect. That record isn't in in the production environment, is that image in LADNN? 

see: https://ursus.library.ucla.edu/catalog?utf8=✓&search_field=all_fields&q="21198%2Fzz002j9526"

or 

https://ursus.library.ucla.edu/catalog?utf8=✓&search_field=all_fields&q=+Diamond+rings

**Comment by andrewbenedictwallace** [comment]
This seems to happen when fields used in the citation are missing in the data record. In this case, it's "Collection", which hasn't been populated for the Will Connell photos.

The same error happens for e.g. https://ursus-test.library.ucla.edu/catalog/4t64gn50h
