### ISSUE TITLE
Ursus collection level record bug

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#302]
When clicking on the collection level record in ursus for LADNN: https://ursus.library.ucla.edu/catalog/7s75dc71j, an error page shows up.

@little9 I believe this is related to the branding banners for collections. See rollbar output below. --Bess

**Comment by emcaulay** [comment]
[Uploading ursus_ladnn_collection_record_2019_03_22.png...]

**Comment by emcaulay** [comment]
![ursus_ladnn_collection_record_2019_03_22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4154ac031c8c0012e97553/125516c66e82c728ace21e0d46fd86893691bca58eedb14d9b5eff9825432467200bad146280e027ad4644535f5e47c3415b3046feeb9539e6f4632adf0f4fffdb7f5a26c56845adbc8a16ee01b371de4f85b7ee8c45c7ee3c20f5979d0d6f405147d4a61760e28b41da59fe41e04850a7163264e373347d4e900c38.png)

**Comment by mark-dce** [comment]
Steps to reproduce:
* Open https://californica.library.ucla.edu
* Search for "la daily news negatives"
* Click on the match that has the "User Collection" badge (i.e. the collection-level record)
* Click on the "View this record in Ursus" just user the title

**EXPECTED BEHAVIOR**
I should see the collection-level page in ursus

**ACTUAL BEHAVIOR**
I get the error page pasted above

**NOTE**
I can't replicate this issue on ursus-test (Test) which is running master 29313040e2dc11c44bb84aad56f55e6ba0374db9

But I do see the issue in Dev, Stage and Prod with are all running Version v1.5.0
